<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>YeyouPlusPlus</AssemblyName>
    <RootNamespace>YeyouPlusPlus</RootNamespace>
    <NuGetAudit>false</NuGetAudit>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <StartupObject>YeyouPlusPlus.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>2.0.3</Version>
    <AssemblyVersion>2.0.3.0</AssemblyVersion>
    <FileVersion>2.0.3.0</FileVersion>
    <ApplicationIcon>..\..\assets\icon\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\icon\app-64.png" Link="Assets\app-64.png" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.WinForms" Version="84.4.10" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net462" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
